// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyirlwkpuljyttfpgnpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aXJsd2twdWxqeXR0ZnBnbnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjI0MzUsImV4cCI6MjA3NDYzODQzNX0.P1_fWmlmfy4LKKggu-pZLTV0qYUF70rjXUSTtPHL_yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});